version: "3.9"
services:
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    networks:
      - vesta
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=development bundle exec rails s -p 3000 -b '0.0.0.0'"

  client:
    build:
      context: ./client
    ports:
      - 8080:8080
    networks:
      - vesta
    command: sh -c "yarn start"

networks:
  vesta:
